### ISSUE TITLE
Create / Manage Temporary Voice Channels

### ISSUE THREAD

**Issue by kringeth000** [GreaterGamersLounge/bot_man#31]
- Create either by command or by joining a "jump channel"
- Destroy after channel empty for time period or on empty
- Possibly limit temp channels per user

**Comment by dracco1993** [comment]
See comment here on permission things:
https://github.com/GreaterGamersLounge/bot_man/issues/32#issuecomment-593548742

**Comment by kringeth000** [comment]
From what I've seen through other bots, usually the owner of the channel is given admin access to that channel specifically, and you just manage it through the Discord UI. Having control only done through bot commands is a nice way to limit what functionality is given to the user, but at the cost of the user experience of managing it. If there are undesirable changes that we don't want the user to make, like hiding the channel from anyone without access for instance, we could have the bot just listen for audits on the channel and negate the changes.

Either way would work honestly.

**Comment by dracco1993** [comment]
New table:
` :server_uid, null: false`
`:inviter_uid, null: false`
`:channel_uid, null: false`
`:active, null: false`
`timestamps`

**Comment by dracco1993** [comment]
TODO:
- [ ] Add table
- [ ] Add command to make a new channel, but only if in voice
  - [ ] Grant `manage_channel` to creator
- [ ] Add command to make jump channel
- [ ] Add jump channel join event
- [ ] Destroy channel on empty
