### ISSUE TITLE
Event Listener / Logger

### ISSUE THREAD

**Issue by dracco1993** [GreaterGamersLounge/bot_man#6]
- Log EVERYTHING
- Timestamp (For sorting and data merge)

**Comment by kringeth000** [comment]
Adding more substance to this Issue:
- Log all available RAW/other events available in the gateway
- Organize and write events to database in a manner that is easy to parse
- Design and deploy database table structure that makes sense


- More cowbell

**Comment by dracco1993** [comment]
Table information:
`event`:
- `id`
- `server_uid`
- `user_uid`
- `data` (jsonb)
- `created_at`
- `updated_at`

**Comment by dracco1993** [comment]
TODO:
- [ ] Create `events` table
- [ ] LOG ALL THE THINGS
